[Interface] CustomerServiceStrategy
- serve(): void

[Interface] Restaurant
- serveCustomer(): void

[Class] RestaurantFactory
- createRestaurant(type: String): Restaurant

[Class] RestaurantManager
- instance: RestaurantManager
- restaurants: List<Restaurant>
- RestaurantManager(): void
+ getInstance(): RestaurantManager
+ addRestaurant(restaurant: Restaurant): void
+ serveCustomers(): void

[Class] ThemedCustomerServiceStrategy
- serve(): void

[Class] ThemedRestaurant
- serveCustomer(): void

[Class] LuxuryRestaurant
- serveCustomer(): void

[Class] FastFoodRestaurant
- serveCustomer(): void

[Class] FastFoodCustomerServiceStrategy
- serve(): void